/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SignWithPrivateKeyOptions {
  content: Buffer;
  cert: Buffer;
  privateKey: Buffer;
  signingTime?: string;
  timestampServer?: string;
}
/** Sign data with the private key. */
export function signWithPrivateKey(options: SignWithPrivateKeyOptions): Buffer;
export interface SignWithP12Options {
  content: Buffer;
  cert: Buffer;
  password?: string;
  signingTime?: string;
  timestampServer?: string;
}
/** Sign data with a P12 container. */
export function signWithP12(options: SignWithP12Options): Buffer;
export interface SignWithGCloudOptions {
  content: Buffer;
  cert: Buffer;
  keyPath: string;
  signingTime?: string;
  timestampServer?: string;
}
/** Sign data with Google Cloud. */
export function signWithGCloud(options: SignWithGCloudOptions): Buffer;
